/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppFarmsRouteImport } from './routes/app.farms'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppPondsPondIdRouteImport } from './routes/app.ponds.$pondId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppPondsPondIdRoute = AppPondsPondIdRouteImport.update({
  id: '/ponds/$pondId',
  path: '/ponds/$pondId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/farms': typeof AppFarmsRoute
  '/app/live': typeof AppLiveRoute
  '/app/': typeof AppIndexRoute
  '/app/ponds/$pondId': typeof AppPondsPondIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/farms': typeof AppFarmsRoute
  '/app/live': typeof AppLiveRoute
  '/app': typeof AppIndexRoute
  '/app/ponds/$pondId': typeof AppPondsPondIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/farms': typeof AppFarmsRoute
  '/app/live': typeof AppLiveRoute
  '/app/': typeof AppIndexRoute
  '/app/ponds/$pondId': typeof AppPondsPondIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/farms'
    | '/app/live'
    | '/app/'
    | '/app/ponds/$pondId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/farms'
    | '/app/live'
    | '/app'
    | '/app/ponds/$pondId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/farms'
    | '/app/live'
    | '/app/'
    | '/app/ponds/$pondId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farms': {
      id: '/app/farms'
      path: '/farms'
      fullPath: '/app/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ponds/$pondId': {
      id: '/app/ponds/$pondId'
      path: '/ponds/$pondId'
      fullPath: '/app/ponds/$pondId'
      preLoaderRoute: typeof AppPondsPondIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFarmsRoute: typeof AppFarmsRoute
  AppLiveRoute: typeof AppLiveRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPondsPondIdRoute: typeof AppPondsPondIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFarmsRoute: AppFarmsRoute,
  AppLiveRoute: AppLiveRoute,
  AppIndexRoute: AppIndexRoute,
  AppPondsPondIdRoute: AppPondsPondIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
